FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /opt/build

COPY MoscowApi/ .

RUN dotnet restore MoscowApi.sln

RUN mkdir /opt/app
RUN dotnet publish MoscowApi.sln -c Release -o /opt/app/

FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /opt/app
COPY --from=build-env /opt/build/ .
WORKDIR /opt/app/MoscowApi/bin/Release/net7.0

EXPOSE 7001

ENTRYPOINT ["dotnet", "MoscowApi.dll"]